/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./products.html",
    "./rentals.html",
    "./about.html",
    "./quality.html",
    "./blogs.html",
    "./gallery.html",
    "./contact.html",
    "./*.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#213145",
        "primary-fixed": "#dae2fd",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#89ceff",
        "inverse-primary": "#bec6e0",
        background: "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "error-container": "#ffdad6",
        "on-secondary-container": "#004666",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#6ffbbe",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#bec6e0",
        "on-error": "#ffffff",
        "primary-container": "#131b2e",
        "on-secondary-fixed-variant": "#004c6e",
        "tertiary-container": "#002113",
        "on-background": "#0b1c30",
        "surface-tint": "#565e74",
        "on-surface-variant": "#45464d",
        "on-primary-fixed": "#131b2e",
        "on-surface": "#0b1c30",
        "surface-container": "#e5eeff",
        "surface-container-low": "#eff4ff",
        secondary: "#006591",
        "on-tertiary-fixed": "#002113",
        outline: "#76777d",
        tertiary: "#000000",
        "secondary-container": "#39b8fd",
        error: "#ba1a1a",
        "secondary-fixed": "#c9e6ff",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#009668",
        "tertiary-fixed-dim": "#4edea3",
        primary: "#000000",
        "on-tertiary-fixed-variant": "#005236",
        "surface-variant": "#d3e4fe",
        "surface-container-high": "#dce9ff",
        "surface-bright": "#f8f9ff",
        "on-primary-container": "#7c839b",
        "inverse-on-surface": "#eaf1ff",
        "on-secondary-fixed": "#001e2f",
        "on-primary-fixed-variant": "#3f465c",
        "surface-container-highest": "#d3e4fe",
        "outline-variant": "#c6c6cd",
        "on-error-container": "#93000a",
        surface: "#f8f9ff",
        brand: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
          950: '#082f49',
        },
        phexal: {
          navy: '#0b1c30',
          dark: '#0f243a',
          blue: '#006591',
          cyan: '#0ea5e9',
          teal: '#00838f',
          emerald: '#059669',
          slate: '#334155',
          border: '#e2e8f0',
        },
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
        pill: "9999px",
      },
      spacing: {
        gutter: "1.5rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "gutter-sm": "1rem",
        "margin-sm": "1rem",
        margin: "2rem",
        "margin-lg": "4rem",
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['"Roboto Mono"', 'monospace'],
        "label-sm": ["Inter", "sans-serif"],
        "headline-sm": ['"Plus Jakarta Sans"', "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "spec-code": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg-mobile": ['"Plus Jakarta Sans"', "sans-serif"],
        "headline-lg-mobile": ['"Plus Jakarta Sans"', "sans-serif"],
        "display-lg": ['"Plus Jakarta Sans"', "sans-serif"],
        "headline-lg": ['"Plus Jakarta Sans"', "sans-serif"],
        "headline-md": ['"Plus Jakarta Sans"', "sans-serif"],
      },
      fontSize: {
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "title-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "label-md": ["13px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "spec-code": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "500" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
      boxShadow: {
        card: "0 4px 20px -2px rgba(11, 28, 48, 0.05), 0 2px 6px -1px rgba(11, 28, 48, 0.03)",
        "card-hover": "0 20px 25px -5px rgba(11, 28, 48, 0.1), 0 8px 10px -6px rgba(11, 28, 48, 0.04)",
        modal: "0 25px 50px -12px rgba(11, 28, 48, 0.25)",
      },
    },
  },
  plugins: [],
}
